name: Acceptance Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint check
        run: npm run lint
      - run: npm i && npx playwright install chromium
      - name: Run tests
        working-directory: ./test
        run: |
          npm i && npx playwright install chromium
          npm run test
